project:
  type: book

book:
  title: "基于ARIMA模型的10年北京天气可视化及其预测"
  author: "Group 19"
  date: now
  chapters:
    - index.qmd
    - humility-predict.ipynb
    - precipitation-predict.ipynb
    - sealevelpressure-predict.ipynb
    - temp-predict.ipynb 
    - windspeed-predict.ipynb
    - summary-report.md

bibliography: references.bib

format:
  html:
    theme: cosmo
